[package]
name = "vhd-shell"
version = "0.1.0"
edition = "2021"

[workspace]
members = [
  "qcow-lib",
  "vhd-lib",
  "vhd-nbdkit",
  ".",
]

[dependencies]
vhd-lib = { path = "vhd-lib" }
qcow-lib = { path = "qcow-lib" }
